name: test-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '>=1.20.3'

    - name: Go Mod Tidy
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
